stages:
  - version
  - package
  - release

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  VERSION_FILE: version.sh
  GIT_DEPTH: 500
  KUBERNETES_VERSION: 1.19.1
  DOCKER_VERSION: 19.03.12
  HELM_VERSION: 3.3.1
  JUPYTER_VERSION: 0.9.1
  SEMVER_VERSION: 4.0.1
  CHART_RELEASER_VERSION: 1.0.0
  CHART_NAME: pysequila

##chart releaser
  CR_OWNER: biodatageeks
  CR_GIT_REPO: charts
  CR_PACKAGE_PATH: ".deploy"
  CR_GIT_BASE_URL: "https://api.github.com/"
  CR_GIT_UPLOAD_URL: "https://uploads.github.com/"


# --------------------------------- STAGE: version ---------------------------------------------------------------------
version-branch:
  stage: version
  image:
    name: mdomke/git-semver:v${SEMVER_VERSION}
    entrypoint: [""]
  script:
    - cd /builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME && git-semver --format x.y.z+m | sed 's/+/-/g' | xargs -I {} echo "export VERSION={}" > $VERSION_FILE
    - cat $VERSION_FILE
  artifacts:
    paths:
      - $VERSION_FILE
  tags: [ docker ]
  except: [ master, tags ]

version-tag:
  stage: version
  image:
    name: mdomke/git-semver:v${SEMVER_VERSION}
    entrypoint: [""]
  script:
    - cd /builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME && git-semver --no-hash --no-pre | xargs -I {} echo "export VERSION={}" > $VERSION_FILE
    - cat $VERSION_FILE
  artifacts:
    paths:
      - $VERSION_FILE
  tags: [ docker ]
  only:
    - tags
  except:
    - branches


package:
  stage: package
  image:
    name: docker:$DOCKER_VERSION
  before_script:
    - source $VERSION_FILE
    - apk --no-cache add curl git openssl bash gettext
    - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v$KUBERNETES_VERSION/bin/linux/amd64/kubectl
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/
    - wget -q https://get.helm.sh/helm-v$HELM_VERSION-linux-amd64.tar.gz -O - | tar -xzO linux-amd64/helm > /usr/local/bin/helm
      && chmod +x /usr/local/bin/helm
      && chmod g+rwx /root
      && mkdir /config
      && chmod g+rwx /config
  script:
    - envsubst < $CHART_NAME/Chart-template.yaml > $CHART_NAME/Chart.yaml
    - helm dep update $CHART_NAME
    - helm lint $CHART_NAME
    - helm package $CHART_NAME --destination .deploy
  artifacts:
    paths:
      - /builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/.deploy/
  except: [ master ]
  tags: [ docker ]

release:
  stage: release
  image:
    name: quay.io/helmpack/chart-releaser:v${CHART_RELEASER_VERSION}
  before_script:
    - source $VERSION_FILE
    - apk --no-cache add curl git bash
    - git config --global user.email "team@biodatageeks.org"
    - git config --global user.name "Biodatageek"
  script:
    - cr upload
    - git pull origin gh-pages
    - git checkout gh-pages
    - cr index -i ./index.yaml -p .deploy --charts-repo https://github.com/${CR_OWNER}/${CR_GIT_REPO}/
    - git add index.yaml
    - git add --force .deploy
    - git commit -m "Release $CHART_NAME-$VERSION"
    - git push https://${CR_TOKEN}@github.com/${CR_OWNER}/${CR_GIT_REPO}.git
  except: [ master ]
  tags: [ docker ]